apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gigfusion.fullname" . }}-scraper
  namespace: {{ include "gigfusion.namespace" . }}
spec:
  schedule: "{{ .Values.scraper.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scraper
            app.kubernetes.io/revision: {{ .Release.Revision | quote }}
        spec:
          serviceAccountName: {{ include "gigfusion.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: scraper
              image: "{{ .Values.image.scraper.repository }}:{{ .Values.image.scraper.tag }}"
              imagePullPolicy: {{ .Values.scraper.imagePullPolicy }}
              env:
                - name: MEILI_URL
                  value: "{{ .Values.meili.url }}"
{{- if .Values.meili.createSecret }}
                - name: MEILI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "gigfusion.fullname" . }}-meili
                      key: masterKey
{{- else }}
                - name: MEILI_API_KEY
                  value: "{{ .Values.meili.masterKey }}"
{{- end }}