apiVersion: v1
kind: Service
metadata:
  name: {{ include "gigfusion.fullname" . }}-meilisearch
  namespace: {{ include "gigfusion.namespace" . }}
  labels:
    app: meilisearch
spec:
  type: {{ .Values.service.meilisearch.type }}
  selector:
    app: meilisearch
  ports:
    - port: {{ .Values.service.meilisearch.port }}
      targetPort: {{ .Values.service.meilisearch.targetPort }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gigfusion.fullname" . }}-frontend
  namespace: {{ include "gigfusion.namespace" . }}
  labels:
    app: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gigfusion.fullname" . }}-backend
  namespace: {{ include "gigfusion.namespace" . }}
  labels:
    app: backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: http