version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
    volumes:
      - ./data/data.ms:/data.ms

  backend:
    build: ./services/backend
    ports:
      - "8000:8000"
    environment:
      - MEILI_URL=http://meilisearch:7700
      - MEILI_API_KEY=${MEILI_MASTER_KEY:-masterKey}
    depends_on:
      - meilisearch

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
