[tool.poetry]
name = "eventing-backend"
version = "0.1.0"
description = "FastAPI backend for eventing"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = "*"
meilisearch = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
