apiVersion: v1
kind: PersistentVolume
metadata:
  name: gigfusion-pv # must match the claim name, use fullname as prefix
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/shared
  claimRef:
    namespace: gigfusion
    name: gigfusion-pvc